# Generated by Django 5.0.4 on 2024-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatamodel',
            name='document',
            field=models.FileField(blank=True, help_text='media Document', null=True, upload_to='media_document'),
        ),
    ]
